name: pages
on:
  push:
    branches:
      - main
    paths:
      - 'apps/demo-app/**'
      - 'libs/ngx-bsn/**'
      - '.github/workflows/pages.yml'

jobs:
  pnpm_install:
    uses: ./.github/workflows/.pnpm_install.yml
    with:
      with_cache: true
  build:
    runs-on: ubuntu-latest
    needs:
      - pnpm_install
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v4
        with:
          path: |
            ./.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: |
          pnpm i --prefer-offline --frozen-lockfile
      - id: build
        run: |
          pnpm exec nx run demo-app:build --baseHref /ngx-bsn/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/apps/demo-app/browser/'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
