name: publish

on:
  push:
    tags:
      - '**'

jobs:
  pnpm_install:
    uses: ./.github/workflows/.pnpm_install.yml
    with:
      with_cache: true
  publish:
    runs-on: ubuntu-latest
    needs:
      - pnpm_install
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: |
          pnpm i --prefer-offline --frozen-lockfile
      - run: |
          pnpm exec nx run ngx-bsn:build
      - run: |
          cp -v README.md LICENSE.md ./dist/libs/ngx-bsn
          pnpm publish ./dist/libs/ngx-bsn --access public --no-git-checks --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
